name: Kubernetes Deploy

on:
  push:
    branches:
      - main


env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  deploy:
    runs-on: "self-hosted"

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Deploy App(Deployment)
        uses: actions-hub/kubectl@master
        with:
          args: apply -f Apps/nginx.yaml

#